version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile 
    ports:
      - "3000:3000"
    volumes:
      - ./client:/Split_your_bill/client
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/Split_your_bill/server